FROM golang:1.25 AS builder

RUN go install go.k6.io/xk6/cmd/xk6@latest

RUN xk6 build v1.7.1 \
    --with github.com/pmalhaire/xk6-mqtt@v0.40.3 \
    --output /k6

FROM alpine:3.21
RUN apk add --no-cache ca-certificates curl
COPY --from=builder /k6 /usr/local/bin/k6
ENTRYPOINT ["k6"]
