// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/ingestion/application (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/ingestion/application/mocks/mock_store.go -package=mocks microbroker-mqtt-edge/internal/modules/ingestion/application Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	message "microbroker-mqtt-edge/internal/common/message"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// GetByTopic mocks base method.
func (m *MockStore) GetByTopic(ctx context.Context, topic string) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTopic", ctx, topic)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTopic indicates an expected call of GetByTopic.
func (mr *MockStoreMockRecorder) GetByTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTopic", reflect.TypeOf((*MockStore)(nil).GetByTopic), ctx, topic)
}

// SaveRawData mocks base method.
func (m *MockStore) SaveRawData(ctx context.Context, msg message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRawData", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRawData indicates an expected call of SaveRawData.
func (mr *MockStoreMockRecorder) SaveRawData(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRawData", reflect.TypeOf((*MockStore)(nil).SaveRawData), ctx, msg)
}
