// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application (interfaces: ShiftReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/live/application/mocks/mock_shift_reader.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application ShiftReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockShiftReader is a mock of ShiftReader interface.
type MockShiftReader struct {
	ctrl     *gomock.Controller
	recorder *MockShiftReaderMockRecorder
	isgomock struct{}
}

// MockShiftReaderMockRecorder is the mock recorder for MockShiftReader.
type MockShiftReaderMockRecorder struct {
	mock *MockShiftReader
}

// NewMockShiftReader creates a new mock instance.
func NewMockShiftReader(ctrl *gomock.Controller) *MockShiftReader {
	mock := &MockShiftReader{ctrl: ctrl}
	mock.recorder = &MockShiftReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShiftReader) EXPECT() *MockShiftReaderMockRecorder {
	return m.recorder
}

// ForMachineWindow mocks base method.
func (m *MockShiftReader) ForMachineWindow(ctx context.Context, machineID string, w domain.Window) (time.Duration, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForMachineWindow", ctx, machineID, w)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForMachineWindow indicates an expected call of ForMachineWindow.
func (mr *MockShiftReaderMockRecorder) ForMachineWindow(ctx, machineID, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForMachineWindow", reflect.TypeOf((*MockShiftReader)(nil).ForMachineWindow), ctx, machineID, w)
}
