// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application (interfaces: StateIntervalReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/live/application/mocks/mock_interval_reader.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application StateIntervalReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/availability/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateIntervalReader is a mock of StateIntervalReader interface.
type MockStateIntervalReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateIntervalReaderMockRecorder
	isgomock struct{}
}

// MockStateIntervalReaderMockRecorder is the mock recorder for MockStateIntervalReader.
type MockStateIntervalReaderMockRecorder struct {
	mock *MockStateIntervalReader
}

// NewMockStateIntervalReader creates a new mock instance.
func NewMockStateIntervalReader(ctrl *gomock.Controller) *MockStateIntervalReader {
	mock := &MockStateIntervalReader{ctrl: ctrl}
	mock.recorder = &MockStateIntervalReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateIntervalReader) EXPECT() *MockStateIntervalReaderMockRecorder {
	return m.recorder
}

// LastOpen mocks base method.
func (m *MockStateIntervalReader) LastOpen(ctx context.Context, machineID string) (domain.StateInterval, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastOpen", ctx, machineID)
	ret0, _ := ret[0].(domain.StateInterval)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LastOpen indicates an expected call of LastOpen.
func (mr *MockStateIntervalReaderMockRecorder) LastOpen(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastOpen", reflect.TypeOf((*MockStateIntervalReader)(nil).LastOpen), ctx, machineID)
}
