// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application (interfaces: AvailabilitySink)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/live/application/mocks/mock_availability_sink.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/live/application AvailabilitySink
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/availability/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvailabilitySink is a mock of AvailabilitySink interface.
type MockAvailabilitySink struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilitySinkMockRecorder
	isgomock struct{}
}

// MockAvailabilitySinkMockRecorder is the mock recorder for MockAvailabilitySink.
type MockAvailabilitySinkMockRecorder struct {
	mock *MockAvailabilitySink
}

// NewMockAvailabilitySink creates a new mock instance.
func NewMockAvailabilitySink(ctrl *gomock.Controller) *MockAvailabilitySink {
	mock := &MockAvailabilitySink{ctrl: ctrl}
	mock.recorder = &MockAvailabilitySinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilitySink) EXPECT() *MockAvailabilitySinkMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockAvailabilitySink) Update(ctx context.Context, s domain.AvailabilitySnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAvailabilitySinkMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAvailabilitySink)(nil).Update), ctx, s)
}
