// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/audit/features/query/application (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/audit/features/query/application/mocks/mock_repository.go -package=mocks microbroker-mqtt-edge/internal/modules/audit/features/query/application Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/audit/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountByTopic mocks base method.
func (m *MockRepository) CountByTopic(ctx context.Context, topic string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTopic", ctx, topic)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTopic indicates an expected call of CountByTopic.
func (mr *MockRepositoryMockRecorder) CountByTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTopic", reflect.TypeOf((*MockRepository)(nil).CountByTopic), ctx, topic)
}

// GetByTopic mocks base method.
func (m *MockRepository) GetByTopic(ctx context.Context, topic string) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTopic", ctx, topic)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTopic indicates an expected call of GetByTopic.
func (mr *MockRepositoryMockRecorder) GetByTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTopic", reflect.TypeOf((*MockRepository)(nil).GetByTopic), ctx, topic)
}
