// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/adapters/inbound/worker (interfaces: StateIngester)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/ingest-state/adapters/inbound/worker/mocks/mock_state_ingester.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/adapters/inbound/worker StateIngester
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/availability/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateIngester is a mock of StateIngester interface.
type MockStateIngester struct {
	ctrl     *gomock.Controller
	recorder *MockStateIngesterMockRecorder
	isgomock struct{}
}

// MockStateIngesterMockRecorder is the mock recorder for MockStateIngester.
type MockStateIngesterMockRecorder struct {
	mock *MockStateIngester
}

// NewMockStateIngester creates a new mock instance.
func NewMockStateIngester(ctrl *gomock.Controller) *MockStateIngester {
	mock := &MockStateIngester{ctrl: ctrl}
	mock.recorder = &MockStateIngesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateIngester) EXPECT() *MockStateIngesterMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockStateIngester) Apply(ctx context.Context, t domain.StateTransition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockStateIngesterMockRecorder) Apply(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockStateIngester)(nil).Apply), ctx, t)
}
