// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/query/application (interfaces: IntervalReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/query/application/mocks/mock_interval_reader.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/query/application IntervalReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/availability/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIntervalReader is a mock of IntervalReader interface.
type MockIntervalReader struct {
	ctrl     *gomock.Controller
	recorder *MockIntervalReaderMockRecorder
	isgomock struct{}
}

// MockIntervalReaderMockRecorder is the mock recorder for MockIntervalReader.
type MockIntervalReaderMockRecorder struct {
	mock *MockIntervalReader
}

// NewMockIntervalReader creates a new mock instance.
func NewMockIntervalReader(ctrl *gomock.Controller) *MockIntervalReader {
	mock := &MockIntervalReader{ctrl: ctrl}
	mock.recorder = &MockIntervalReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntervalReader) EXPECT() *MockIntervalReaderMockRecorder {
	return m.recorder
}

// ByMachineRange mocks base method.
func (m *MockIntervalReader) ByMachineRange(ctx context.Context, machineID string, from, to time.Time) ([]domain.StateInterval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByMachineRange", ctx, machineID, from, to)
	ret0, _ := ret[0].([]domain.StateInterval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByMachineRange indicates an expected call of ByMachineRange.
func (mr *MockIntervalReaderMockRecorder) ByMachineRange(ctx, machineID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByMachineRange", reflect.TypeOf((*MockIntervalReader)(nil).ByMachineRange), ctx, machineID, from, to)
}
