// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/config/application (interfaces: ShiftStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/config/application/mocks/mock_shift_store.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/config/application ShiftStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockShiftStore is a mock of ShiftStore interface.
type MockShiftStore struct {
	ctrl     *gomock.Controller
	recorder *MockShiftStoreMockRecorder
	isgomock struct{}
}

// MockShiftStoreMockRecorder is the mock recorder for MockShiftStore.
type MockShiftStoreMockRecorder struct {
	mock *MockShiftStore
}

// NewMockShiftStore creates a new mock instance.
func NewMockShiftStore(ctrl *gomock.Controller) *MockShiftStore {
	mock := &MockShiftStore{ctrl: ctrl}
	mock.recorder = &MockShiftStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShiftStore) EXPECT() *MockShiftStoreMockRecorder {
	return m.recorder
}

// ForMachineWindow mocks base method.
func (m *MockShiftStore) ForMachineWindow(ctx context.Context, machineID string, w domain.Window) (time.Duration, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForMachineWindow", ctx, machineID, w)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForMachineWindow indicates an expected call of ForMachineWindow.
func (mr *MockShiftStoreMockRecorder) ForMachineWindow(ctx, machineID, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForMachineWindow", reflect.TypeOf((*MockShiftStore)(nil).ForMachineWindow), ctx, machineID, w)
}

// Upsert mocks base method.
func (m *MockShiftStore) Upsert(ctx context.Context, s domain.Shift) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockShiftStoreMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockShiftStore)(nil).Upsert), ctx, s)
}
