// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/application (interfaces: IntervalStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/ingest-state/application/mocks/mock_interval_store.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/application IntervalStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microbroker-mqtt-edge/internal/modules/oee/availability/domain"
	domain0 "microbroker-mqtt-edge/internal/modules/oee/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIntervalStore is a mock of IntervalStore interface.
type MockIntervalStore struct {
	ctrl     *gomock.Controller
	recorder *MockIntervalStoreMockRecorder
	isgomock struct{}
}

// MockIntervalStoreMockRecorder is the mock recorder for MockIntervalStore.
type MockIntervalStoreMockRecorder struct {
	mock *MockIntervalStore
}

// NewMockIntervalStore creates a new mock instance.
func NewMockIntervalStore(ctrl *gomock.Controller) *MockIntervalStore {
	mock := &MockIntervalStore{ctrl: ctrl}
	mock.recorder = &MockIntervalStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntervalStore) EXPECT() *MockIntervalStoreMockRecorder {
	return m.recorder
}

// CloseOpen mocks base method.
func (m *MockIntervalStore) CloseOpen(ctx context.Context, machineID string, endedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseOpen", ctx, machineID, endedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseOpen indicates an expected call of CloseOpen.
func (mr *MockIntervalStoreMockRecorder) CloseOpen(ctx, machineID, endedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseOpen", reflect.TypeOf((*MockIntervalStore)(nil).CloseOpen), ctx, machineID, endedAt)
}

// LastOpen mocks base method.
func (m *MockIntervalStore) LastOpen(ctx context.Context, machineID string) (domain.StateInterval, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastOpen", ctx, machineID)
	ret0, _ := ret[0].(domain.StateInterval)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LastOpen indicates an expected call of LastOpen.
func (mr *MockIntervalStoreMockRecorder) LastOpen(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastOpen", reflect.TypeOf((*MockIntervalStore)(nil).LastOpen), ctx, machineID)
}

// OpenInterval mocks base method.
func (m *MockIntervalStore) OpenInterval(ctx context.Context, machineID string, state domain0.MachineState, startedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenInterval", ctx, machineID, state, startedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenInterval indicates an expected call of OpenInterval.
func (mr *MockIntervalStoreMockRecorder) OpenInterval(ctx, machineID, state, startedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenInterval", reflect.TypeOf((*MockIntervalStore)(nil).OpenInterval), ctx, machineID, state, startedAt)
}
