// Code generated by MockGen. DO NOT EDIT.
// Source: microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/application (interfaces: StateObserver)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/oee/availability/features/ingest-state/application/mocks/mock_state_observer.go -package=mocks microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/application StateObserver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	application "microbroker-mqtt-edge/internal/modules/oee/availability/features/ingest-state/application"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateObserver is a mock of StateObserver interface.
type MockStateObserver struct {
	ctrl     *gomock.Controller
	recorder *MockStateObserverMockRecorder
	isgomock struct{}
}

// MockStateObserverMockRecorder is the mock recorder for MockStateObserver.
type MockStateObserverMockRecorder struct {
	mock *MockStateObserver
}

// NewMockStateObserver creates a new mock instance.
func NewMockStateObserver(ctrl *gomock.Controller) *MockStateObserver {
	mock := &MockStateObserver{ctrl: ctrl}
	mock.recorder = &MockStateObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateObserver) EXPECT() *MockStateObserverMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockStateObserver) Apply(t application.StateTransition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Apply", t)
}

// Apply indicates an expected call of Apply.
func (mr *MockStateObserverMockRecorder) Apply(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockStateObserver)(nil).Apply), t)
}
